// Assets.tsx - Department data for the college website
export const Assets = {
  DepartmentData: {
    cse: {
      name: 'Computer Science and Engineering',
      heroImage: 'https://vignaniit.edu.in/images/cse.jpg',
      about: "The Department of Computer Science and Engineering at the Vignan's Institute of Information Technology, Visakhapatnam, was established in the year 2002 and provides a perfect academic and research environment complemented by excellence in teaching.The Department offers B.Tech., M.Tech (CSE and SE) Programmes. The Department has a comprehensive curriculum on topics related to all aspects of Computer Science and Engineering with an emphasis on practical learning. The course structure is up-to-date and includes courses on nascent topics to equip our students with the latest developments in Computer Science and Engineering.The Department has state-of-the-art infrastructure and computing equipment supported by high-speed Ethernet and wireless networks. Student organization like ACM Chapter is active throughout the year.Our faculty members aim at delivering top class education, blending their rich research experience with classroom teaching. The Department has undertaken many research projects funded both by government agencies and foreign research society.CSE Department currently has 49 full-time faculty members, some of whom are cross-listed with related departments such as Basic Science, EEE, ECE, Mechanical, etc. We also draw on the expertise of a few Visiting Professors from Foreign Universities and Industry. The Department has UG intake of 240 students. Roughly 80% of these students finally getting jobs in Industries, and 10-15% are going for Master Programmes and Research.",
      hodMessage: "A warm welcome to CSE@Vignan's Institute of Information Technology……..CSE (Computer Science and Engineering) at the Vignan's Institute of Information Technology has its seeds in the erstwhile Institute set up in 2002. While at inception, it was primarily focused on academics, the ambit expanded on the journey to include M.Tech Programmes, Research and Placements, Research Center, and NBA Accreditations (2009 and 2017), leading to the current name.CSE Department focuses on academics, creative research, and good placements in three broad areas of computer science:Computer Science and Engineering, including basic concepts, number theory, complexity theory, graph theory, coding theory, algorithms, data structures, cryptography and security.Computer Systems and Software, including computer architecture, operating systems, programming languages, compilers, software engineering, database systems, graphics and visualization, communication networks, and distributed computing.Intelligent Systems, including data mining, machine learning, artificial intelligence, optimization, information retrieval, and scientific applications.These academics and research activities find expression through publications in premier international journals and conferences. CSE is also involved in numerous scientific initiatives at the institute, state, national, and international levels, including sponsored research projects, consultancy, government programs, hackathons, journal editorship, workshops, and conferences.",
      hodName: 'Dr. Mohan Mahanty',
      hodImage: 'http://vignaniit.edu.in/images/mohan1.png',
      vision: "To become a nationally recognized leader in computer science education, research, and innovation, producing graduates who are highly sought after by industry and academia.",
      mission: "To provide a dynamic and creative learning environment that fosters a deep understanding of computer science fundamentals, encourages practical problem-solving, and inspires lifelong learning and ethical responsibility.",
    },
    aids: {
      name: 'Artificial Intelligence and Data Science',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Department of Artificial Intelligence and Data Science focuses on cutting-edge technologies in machine learning, neural networks, big data analytics, and intelligent systems design. Our program prepares students to meet the growing demand for AI professionals and data scientists.",
      hodMessage: "Welcome to the Department of AI & Data Science. Our department is at the forefront of research and education in artificial intelligence and data science technologies. We are committed to preparing our students for the future of technology, where data-driven decision making and intelligent systems are increasingly important.",
      hodName: 'Dr. Satya Prakash',
      hodImage: 'http://vignaniit.edu.in/images/faculty1.jpg',
      vision: "To be a leading center for AI and data science education and research, developing solutions that address real-world challenges through intelligent systems and data analysis.",
      mission: "To provide comprehensive education in AI and data science, foster innovation, and promote ethical use of AI technologies and data-driven approaches.",
    },
    cses: {
      name: 'Advanced CSE (AI, Cyber Security, Data Science)',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Advanced CSE program combines core computer science with specialized tracks in AI technologies, cybersecurity protocols, and data science methodologies. This multi-disciplinary approach equips students with the expertise needed for the most in-demand tech roles.",
      hodMessage: "Welcome to Advanced CSE. Our department offers a unique blend of specialized tracks that prepare students for the most challenging and rewarding careers in technology. With focuses on AI, cybersecurity, and data science, our graduates are ready to tackle complex problems across industries.",
      hodName: 'Dr. Rajesh Kumar',
      hodImage: 'http://vignaniit.edu.in/images/faculty2.jpg',
      vision: "To develop technical leaders equipped to tackle complex challenges at the intersection of AI, security, and data analytics.",
      mission: "To provide specialized education with industry-aligned curriculum that prepares students for emerging technological challenges and opportunities.",
    },
    civil: {
      name: 'Civil Engineering',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Department of Civil Engineering provides comprehensive education in structural engineering, construction management, transportation systems, and infrastructure development. Our program emphasizes practical skills alongside theoretical knowledge.",
      hodMessage: "Welcome to the Department of Civil Engineering. We focus on developing engineers who can design and implement sustainable infrastructure solutions that meet society's evolving needs. Our department combines traditional civil engineering principles with modern techniques and environmental considerations.",
      hodName: 'Dr. Arun Sharma',
      hodImage: 'http://vignaniit.edu.in/images/faculty3.jpg',
      vision: "To develop skilled civil engineers capable of designing sustainable infrastructure for society's evolving needs.",
      mission: "To impart technical knowledge and practical skills in civil engineering with emphasis on innovation and sustainability.",
    },
    eee: {
      name: 'Electrical & Electronics Engineering',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Department of Electrical & Electronics Engineering offers education in power systems, control systems, electrical machinery, and renewable energy technologies. Our program prepares students for careers in the rapidly evolving energy sector.",
      hodMessage: "Welcome to the Department of Electrical & Electronics Engineering. Our department focuses on both traditional electrical engineering fundamentals and cutting-edge technologies in power electronics, renewable energy, and smart grids. We are committed to preparing our students for the future of energy systems.",
      hodName: 'Dr. Priya Gupta',
      hodImage: 'http://vignaniit.edu.in/images/faculty4.jpg',
      vision: "To be a center of excellence in electrical engineering education, producing engineers who drive innovation in power and energy sectors.",
      mission: "To provide quality education in electrical engineering fundamentals and applications, with focus on practical skills and research.",
    },
    ece: {
      name: 'Electronics & Computer Engineering',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Electronics & Computer Engineering program combines electronics hardware knowledge with computer systems and software development skills. This multidisciplinary approach prepares students for careers at the intersection of hardware and software.",
      hodMessage: "Welcome to the Department of Electronics & Computer Engineering. Our department bridges the gap between hardware and software domains, preparing versatile engineers who can work across the full technology stack. We focus on embedded systems, IoT, and hardware-software integration.",
      hodName: 'Dr. Vikram Singh',
      hodImage: 'http://vignaniit.edu.in/images/faculty5.jpg',
      vision: "To create engineers with expertise in both hardware and software domains, capable of developing integrated solutions for complex technological challenges.",
      mission: "To provide comprehensive education bridging electronics and computing, preparing versatile engineers for the technology industry.",
    },
    ecm: {
      name: 'Electronics & Communication Engineering',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Department of Electronics & Communication Engineering offers education in signal processing, telecommunications, VLSI design, and embedded systems. Our program prepares students for careers in the communications and electronics industry.",
      hodMessage: "Welcome to the Department of Electronics & Communication Engineering. Our department is dedicated to preparing students for careers in the rapidly evolving field of electronics and telecommunications. We emphasize both theoretical knowledge and practical skills in areas like VLSI design, embedded systems, and communication networks.",
      hodName: 'Dr. Neeraj Patel',
      hodImage: 'http://vignaniit.edu.in/images/faculty6.jpg',
      vision: "To be a premier department producing electronics engineers capable of technological innovation in communications and electronics sectors.",
      mission: "To provide quality education in electronics and communication with emphasis on practical skills and research opportunities.",
    },
    it: {
      name: 'Information Technology',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Department of Information Technology focuses on information systems, networks, database management, and enterprise solutions. Our program prepares students for careers in IT infrastructure management and software development.",
      hodMessage: "Welcome to the Department of Information Technology. Our department specializes in preparing students for careers in enterprise IT solutions, cloud computing, and information systems management. We focus on both technical skills and business applications of technology.",
      hodName: 'Dr. Anand Kumar',
      hodImage: 'http://vignaniit.edu.in/images/faculty7.jpg',
      vision: "To develop IT professionals skilled in designing, implementing, and managing information systems for organizational needs.",
      mission: "To provide education in IT fundamentals and applications with focus on enterprise-level solutions and emerging technologies.",
    },
    me: {
      name: 'Mechanical Engineering',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Department of Mechanical Engineering provides education in mechanics, thermodynamics, manufacturing processes, and mechanical design. Our program prepares students for careers in various industries requiring mechanical expertise.",
      hodMessage: "Welcome to the Department of Mechanical Engineering. Our department offers comprehensive training in both traditional mechanical engineering principles and cutting-edge technologies like CAD/CAM, automation, and advanced materials. We prepare our students for careers across manufacturing, automotive, aerospace, and many other industries.",
      hodName: 'Dr. Ravi Verma',
      hodImage: 'http://vignaniit.edu.in/images/faculty8.jpg',
      vision: "To develop mechanical engineers capable of designing and implementing innovative solutions for industry and society.",
      mission: "To provide comprehensive mechanical engineering education combining theory with practical applications and research opportunities.",
    },
    basic: {
      name: 'Basic Science & Humanities',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The Department of Basic Sciences & Humanities provides foundational education in physics, chemistry, mathematics, and communication skills essential for engineering studies. Our courses build the scientific and humanistic foundation for technical education.",
      hodMessage: "Welcome to the Department of Basic Sciences & Humanities. Our department plays a crucial role in building strong scientific foundations and communication skills for engineering students. We believe that technical excellence must be complemented by humanistic perspectives for holistic professional development.",
      hodName: 'Dr. Sunita Sharma',
      hodImage: 'http://vignaniit.edu.in/images/faculty9.jpg',
      vision: "To build strong scientific foundations and humanistic perspectives among engineering students for holistic development.",
      mission: "To impart quality education in basic sciences and humanities that complements technical education in engineering disciplines.",
    },
    aiml: {
      name: 'AI & Machine Learning',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The postgraduate program in AI & Machine Learning focuses on advanced artificial intelligence theories, machine learning algorithms, and their practical applications. Students gain expertise in neural networks, deep learning, and AI research methods.",
      hodMessage: "Welcome to the AI & Machine Learning postgraduate program. Our program is designed for students who want to specialize in the rapidly growing field of artificial intelligence and machine learning. We combine theoretical knowledge with practical applications and research opportunities.",
      hodName: 'Dr. Pradeep Kumar',
      hodImage: 'http://vignaniit.edu.in/images/faculty10.jpg',
      vision: "To develop AI specialists with deep theoretical knowledge and practical skills to lead innovation in intelligent systems.",
      mission: "To provide cutting-edge education in AI and machine learning through research-oriented and application-focused curriculum.",
    },
    digi: {
      name: 'Digital Electronics & Communication Systems',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The postgraduate program in Digital Electronics & Communication Systems specializes in digital electronics design, signal processing, and modern communication systems. Students gain expertise in advanced communication protocols and digital system design.",
      hodMessage: "Welcome to the Digital Electronics & Communication Systems postgraduate program. Our program prepares specialists in digital electronics and advanced communication systems with both theoretical knowledge and practical skills. We focus on emerging technologies like 5G, IoT communication, and next-generation wireless systems.",
      hodName: 'Dr. Meena Kumari',
      hodImage: 'http://vignaniit.edu.in/images/faculty11.jpg',
      vision: "To develop specialists in digital electronics and communication systems who can lead technological advancements in the field.",
      mission: "To provide advanced education and research opportunities in digital electronics and communications with industry-relevant skills.",
    },
    mba: {
      name: 'Master of Business Administration',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The MBA program focuses on leadership, strategic management, finance, marketing, and operations management. Students gain comprehensive business knowledge and management skills for corporate careers.",
      hodMessage: "Welcome to the MBA program. Our curriculum is designed to develop business leaders with strategic thinking, analytical skills, and ethical values. We emphasize case-study based learning, industry exposure, and leadership development throughout the program.",
      hodName: 'Dr. Sanjay Kapoor',
      hodImage: 'http://vignaniit.edu.in/images/faculty12.jpg',
      vision: "To develop business leaders with strategic thinking, ethical values, and global perspective to excel in the corporate world.",
      mission: "To provide quality management education combining theory, practical skills, and industry exposure for holistic development.",
    },
    mca: {
      name: 'Master of Computer Applications',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The MCA program focuses on advanced software development, system design, database management, and IT project management. Students gain technical skills and managerial capabilities for the software industry.",
      hodMessage: "Welcome to the MCA program. Our curriculum is designed to develop IT professionals with advanced technical skills and project management capabilities. We emphasize hands-on programming experience, software development methodologies, and exposure to emerging technologies.",
      hodName: 'Dr. Vivek Sharma',
      hodImage: 'http://vignaniit.edu.in/images/faculty13.jpg',
      vision: "To develop IT professionals with advanced technical skills and managerial capabilities for the software industry.",
      mission: "To provide comprehensive education in computer applications combining theory, practical skills, and project experience.",
    },
    pcse: {
      name: 'Computer Science & Engineering (PG)',
      heroImage: 'https://sirgurudasmahavidyalaya.ac.in/public/storage/department/OlRFpc01GsaXMC1Bj51zNXINmJCweOlRLtxaHncN.jpg',
      about: "The postgraduate program in Computer Science & Engineering focuses on advanced algorithms, distributed systems, and specialized computing domains. Students engage in research and gain expertise in cutting-edge computing technologies.",
      hodMessage: "Welcome to the postgraduate program in Computer Science & Engineering. Our research-oriented curriculum prepares students for advanced careers in computing and provides a foundation for doctoral studies. We emphasize both theoretical depth and practical implementation skills.",
      hodName: 'Dr. Ankit Singh',
      hodImage: 'http://vignaniit.edu.in/images/faculty14.jpg',
      vision: "To develop computer science specialists with advanced knowledge and research capabilities.",
      mission: "To provide cutting-edge education in advanced computing with emphasis on research and innovation.",
    }
  }
};
